### ISSUE TITLE
1 wrong location in New Hampshire in 1984

### ISSUE THREAD

**Issue by lukeave** [MappingtheGayGuides/mgg-website#39]
1 out of 22 locations in New Hampshire in 1984 is wrong:
* Urghyli Lounge
    Should be in Lebanon but shows up in Nebraska.

**Comment by regan008** [comment]
Great, lets identify the correct location and update in Airtable. If you can't find it and it hasn't already been located in a previous year, lets use the general city coordinates as defined by this google geocoder: https://developers-dot-devsite-v2-prod.appspot.com/maps/documentation/utils/geocoder/
