### ISSUE TITLE
1 missing and 1 wrong locations in North Carolina in 1984

### ISSUE THREAD

**Issue by lukeave** [MappingtheGayGuides/mgg-website#41]
1 out of 95 locations in North Carolina in 1984 is missing from the map.

1 other location is wrong on the map:
* M.C.C.
    Should be in Greenville, NC; shows up in Greenville, SC.

**Comment by regan008** [comment]
The location that didn't show up had NA for coordinates. Should have been marked as unclear (no address, just a phone number) but instead was geocoded.

#4160, MCC Greenville NC is more interesting. It is indeed listed under NC in the guides but I suspect that is a mistake on Damron's part. From what I can tell, this isn't an address in Greenville NC but it is in Greenville SC. I suspect its an error in Damron's guides but given I have no proof of that and it only shows up in two years I'm going to leave it as Damron has it. I made a note and listed it as unverified/general coordinates in Greenville NC.
