### ISSUE TITLE
2 missing locations in Texas in 1984

### ISSUE THREAD

**Issue by lukeave** [MappingtheGayGuides/mgg-website#42]
2 out of 340 locations in Texas in 1984 do not show up on the map.

**Comment by regan008** [comment]
@lukeave great catch. I'm going to put you in charge of investigating and remedying these location errors. Can you investigate using the complete data base and see which locations are missing? We'll make the change directly in that base. Once you've figured out which locations are missing we can talk about how to fix these types of issues.

**Comment by regan008** [comment]
Dallas Gay News
Capitol of Texas (travel service)

All have addresses so its unclear why geocoding didn't work. Perhaps because they each have a unit number, i.e. `#102` next to the address. 

Resolved.
