### ISSUE TITLE
Territories dropdown is not in alphabetical order 

### ISSUE THREAD

**Issue by lukeave** [MappingtheGayGuides/mgg-website#56]
I.e., North Carolina comes before Nevada.

**Comment by regan008** [comment]
@lukeave you can edit this by moving the entire dropdown entry (everything betweeen the `<option>` and `</option>` tags. You'll find the relevant code in: content/viz/main-map.md

**Here are the steps for submitting this change:** 
1. clone your forked repository to your computer.
2. Edit the file
3. commit your changes and reference the issue
4. push your changes to your fork
5. In github, submit a pull request from the original repository. [Here is some documentation.](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork).
